- hosts: all
  tasks:

  - file:
      state: directory
      path: "/dvd"

  - mount:
      src: "/dev/cdrom"
      path: "/dvd"
      fstype: "iso9660"
      state: mounted

  - yum_repository:
      baseurl: "/dvd1/AppStream"
      name: "mydvd1"
      description: "This is dvd1ffff"
      gpgcheck: no

  - yum_repository:
      name: "mydvd2"
      description: "This is dvd1sss"
      baseurl: "/dvd1/BaseOS"
      gpgcheck: no

  - yum_repository:
      baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"
      name: "docker-yum"
      description: "Docker Repo"
      state: present
      gpgcheck: no

  - package:
      name: "python3"
      state: present 
 
  - package:
      name: "docker-ce-18.09.1-3.el7.x86_64"
      state: present

  - service:
      name: "docker"
      state: started
      enabled: yes

  - pip:
      name: "docker-py"

  - community.general.docker_image:
      name: "httpd"
      source: pull

  - file:
      path: "/webpages"
      state: directory

  - copy:
      src: "/root/index.html" 
      dest: "/webpages"
 
  - community.general.docker_container:
      name: "myos"
      image: "httpd"
      exposed_ports: "80"
      ports: "8998:80"
      volumes: "/webpages:/usr/local/apache2/htdocs/"

